
title: Venkatesh Umamaheswaran CV
url: 'https://github.com/venkateshuv'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Venkatesh Umamaheswaran
tagline: Data Science Enthusiast
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: vumamahe@uncc.edu
phone: 704 904 0728
website: venkateshuv/ #do not add http://
linkedin: venkatesh-umamaheswaran
github: venkateshuv
twitter: '@Venkat_UV'

#Update all the sections by editing the files inside _includes folder.
